paths:
  jquery: jquery.min
  app: backbone/app
  header: backbone/apps/header/header_app
shim:
  underscore:
    exports: _
  backbone:
    deps:
      - jquery
      - underscore
    exports: Backbone
  marionette:
    deps:
      - backbone
    exports: Marionette